admin_order_payments_index:
  path: /payments
  methods: [GET]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderPaymentController::indexAction
    _legacy_controller: AdminOrderPayments
    _legacy_link: AdminOrderPayments

admin_order_payments_search:
  path: /payments/search
  methods: [POST]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderPaymentController::searchAction
    _legacy_controller: AdminOrderPayments
    _legacy_link: AdminOrderPayments

# ====== Order Payment API

order_payment_get_all:
  path: /{orderId}/payment
  methods: [GET]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderPaymentController::getAllAction
  options:
    expose: true

order_payment_add:
  path: /{orderId}/payment
  methods: [POST]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderPaymentController::addAction
  options:
    expose: true

order_payment_edit:
  path: /{orderId}/payment/{paymentId}
  methods: [POST]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderPaymentController::editAction
  requirements:
    paymentId: \d+
    orderId: \d+
  options:
    expose: true

order_payment_delete:
  path: /{orderId}/payment/{paymentId}
  methods: [DELETE]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderPaymentController::deleteAction
  requirements:
    orderId: \d+
    paymentId: \d+
  options:
    expose: true

order_payment_download:
  path: /{orderId}/payment/{paymentId}/document/{documentId}
  methods: [GET]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderPaymentController::downloadAction
  requirements:
    orderId: \d+
    paymentId: \d+
    documentId: \d+
  options:
    expose: true

order_payment_i18n:
  path: /i18n
  methods: [GET]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Api\I18nController::listTranslationAction
  options:
    expose: true