admin_order_invoices_index:
  path: /invoices
  methods: [GET]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderInvoiceController::indexAction
    _legacy_controller: AdminOrderInvoices
    _legacy_link: AdminOrderInvoices

admin_order_invoices_search:
  path: /invoices
  methods: [POST]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderInvoiceController::searchAction
    _legacy_controller: AdminOrderInvoices
    _legacy_link: AdminOrderInvoices

# ====== Order Invoice API ======

order_invoice_get_all:
  path: /{orderId}/invoice
  methods: [GET]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderInvoiceController::getAllAction
  requirements:
    orderId: \d+
  options:
    expose: true

order_invoice_add:
  path: /{orderId}/invoice
  methods: [POST]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderInvoiceController::addAction
  requirements:
    orderId: \d+
  options:
    expose: true

order_invoice_edit:
  path: /{orderId}/invoice/{orderInvoiceId}
  methods: [POST]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderInvoiceController::editAction
  requirements:
    orderId: \d+
    orderInvoiceId: \d+
  options:
    expose: true

order_invoice_delete:
  path: /{orderId}/invoice/{orderInvoiceId}
  methods: [DELETE]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderInvoiceController::deleteAction
  requirements:
      orderId: \d+
      orderInvoiceId: \d+
  options:
    expose: true

order_invoice_download:
  path: /{orderId}/invoice/{orderInvoiceId}/document/{documentId}
  methods: [GET]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderInvoiceController::downloadAction
  requirements:
    orderId: \d+
    orderInvoiceId: \d+
    documentId: \d+
  options:
    expose: true