order_invoice_index:
  path: /invoices
  methods: [GET]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderInvoiceController::indexAction
    _legacy_controller: AdminOrderInvoices
    _legacy_link: AdminOrderInvoices

# ====== Order Invoice API ======

order_invoice_get_all:
  path: /
  methods: [GET]
  defaults:
    _controller: Novanta\OrderPayment\Controller\Admin\OrderInvoiceController::getAllAction