services:
  OrderPayment\Repository\OrderPaymentDocumentRepository:
    class: OrderPayment\Repository\OrderPaymentDocumentRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - OrderPayment\Entity\OrderPaymentDocument
