services:
  Novanta\OrderPayment\Repository\OrderPaymentDocumentRepository:
    class: Novanta\OrderPayment\Repository\OrderPaymentDocumentRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Novanta\OrderPayment\Entity\OrderPaymentDocument
