services:
  _defaults:
    public: true

  # ============== Queries

  Novanta\OrderPayment\Adapter\OrderPayment\QueryHandler\GetOrderPaymentsHandler:
    class: 'Novanta\OrderPayment\Adapter\OrderPayment\QueryHandler\GetOrderPaymentsHandler'
    arguments:
      - '@Novanta\OrderPayment\Repository\OrderPaymentDocumentRepository'
      - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
      - '@doctrine.orm.entity_manager'
    autoconfigure: true

  # ============== Commands

  Novanta\OrderPayment\Adapter\OrderPayment\CommandHandler\EditOrderPaymentHandler:
    class: 'Novanta\OrderPayment\Adapter\OrderPayment\CommandHandler\EditOrderPaymentHandler'
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@prestashop.core.command_bus'
      - '@Novanta\OrderPayment\Adapter\OrderPayment\Repository\OrderPaymentRepository'
    autoconfigure: true

  Novanta\OrderPayment\Adapter\OrderPayment\CommandHandler\DeleteOrderPaymentHandler:
    class: 'Novanta\OrderPayment\Adapter\OrderPayment\CommandHandler\DeleteOrderPaymentHandler'
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@prestashop.core.command_bus'
      - '@Novanta\OrderPayment\Adapter\OrderPayment\Repository\OrderPaymentRepository'
    autoconfigure: true

  Novanta\OrderPayment\Adapter\OrderPayment\CommandHandler\AddOrderPaymentHandler:
    class: 'Novanta\OrderPayment\Adapter\OrderPayment\CommandHandler\AddOrderPaymentHandler'
    arguments:
      - '@prestashop.core.command_bus'
      - '@Novanta\OrderPayment\Adapter\OrderPayment\Repository\OrderPaymentRepository'
    autoconfigure: true
